  // Add IDs to your tech stack options
  export const techStackOptions = [
    { value: 'WebDevelopment', label: 'Web Development' },
    { value: 'MobileAppDevelopment', label: 'Mobile App Development' },
    { value: 'DataScience', label: 'Data Science' },
    { value: 'MachineLearning', label: 'Machine Learning' },
    { value: 'ArtificialIntelligence', label: 'Artificial Intelligence' },
    { value: 'CloudComputing', label: 'Cloud Computing' },
    { value: 'Cybersecurity', label: 'Cybersecurity' },
    { value: 'DatabaseManagement', label: 'Database Management' },
    { value: 'DevOps', label: 'DevOps' },
    { value: 'FullStackDevelopment', label: 'Full Stack Development' },
    { value: 'FrontendDevelopment', label: 'Frontend Development' },
    { value: 'BackendDevelopment', label: 'Backend Development' },
    { value: 'UIUXDesign', label: 'UI/UX Design' },
    { value: 'BigData', label: 'Big Data' },
    { value: 'Blockchain', label: 'Blockchain' },
    { value: 'IoT', label: 'Internet of Things (IoT)' },
    { value: 'ARVRDevelopment', label: 'AR/VR Development' },
    { value: 'Robotics', label: 'Robotics' },
    { value: 'GameDevelopment', label: 'Game Development' },
    { value: 'NetworkAdministration', label: 'Network Administration' },
    { value: 'SystemAdministration', label: 'System Administration' },
    { value: 'SoftwareTesting', label: 'Software Testing' },
    { value: 'ITConsulting', label: 'IT Consulting' },
    { value: 'E-commerce', label: 'E-commerce' },
    { value: 'HealthIT', label: 'Health IT' },
    { value: 'FinancialTechnology', label: 'Financial Technology (FinTech)' },
    { value: 'EducationalTechnology', label: 'Educational Technology (EdTech)' },
    { value: 'AIChatbots', label: 'AI Chatbots' },
    { value: 'CloudSecurity', label: 'Cloud Security' },
    { value: 'QuantumComputing', label: 'Quantum Computing' },
    { value: 'DataEngineering', label: 'Data Engineering' },
    { value: 'RemoteSensing', label: 'Remote Sensing' },
    { value: 'Virtualization', label: 'Virtualization' },
    { value: 'EmbeddedSystems', label: 'Embedded Systems' },
    { value: 'Bioinformatics', label: 'Bioinformatics' },
    { value: 'GeographicInformationSystems', label: 'Geographic Information Systems (GIS)' },
    { value: 'CloudStorage', label: 'Cloud Storage' },
    { value: 'WirelessCommunication', label: 'Wireless Communication' },
    { value: 'WebDesign', label: 'Web Design' },
    { value: 'DataAnalytics', label: 'Data Analytics' },
    { value: 'BusinessIntelligence', label: 'Business Intelligence' },
    { value: 'CRMSoftware', label: 'CRM Software' },
    { value: 'SupplyChainManagement', label: 'Supply Chain Management' },
    { value: 'Telecommunications', label: 'Telecommunications' },
    { value: 'SaaS', label: 'Software as a Service (SaaS)' },
    { value: 'PaaS', label: 'Platform as a Service (PaaS)' },
    { value: 'IaaS', label: 'Infrastructure as a Service (IaaS)' },
    { value: 'MobileAppDevelopment', label: 'Mobile App Development' },
    { value: 'DataScience', label: 'Data Science' },
    { value: 'MachineLearning', label: 'Machine Learning' },
    { value: 'ArtificialIntelligence', label: 'Artificial Intelligence' },
    { value: 'CloudComputing', label: 'Cloud Computing' },
    { value: 'Cybersecurity', label: 'Cybersecurity' },
    { value: 'DatabaseManagement', label: 'Database Management' },
    { value: 'DevOps', label: 'DevOps' },
    { value: 'FullStackDevelopment', label: 'Full Stack Development' },
    { value: 'FrontendDevelopment', label: 'Frontend Development' },
    { value: 'BackendDevelopment', label: 'Backend Development' },
    { value: 'UIUXDesign', label: 'UI/UX Design' },
    { value: 'BigData', label: 'Big Data' },
    { value: 'Blockchain', label: 'Blockchain' },
    { value: 'IoT', label: 'Internet of Things (IoT)' },
    { value: 'ARVRDevelopment', label: 'AR/VR Development' },
    { value: 'Robotics', label: 'Robotics' },
    { value: 'GameDevelopment', label: 'Game Development' },
    { value: 'NetworkAdministration', label: 'Network Administration' },
    { value: 'SystemAdministration', label: 'System Administration' },
    { value: 'SoftwareTesting', label: 'Software Testing' },
    { value: 'ITConsulting', label: 'IT Consulting' },
    { value: 'E-commerce', label: 'E-commerce' },
    { value: 'HealthIT', label: 'Health IT' },
    { value: 'FinancialTechnology', label: 'Financial Technology (FinTech)' },
    { value: 'EducationalTechnology', label: 'Educational Technology (EdTech)' },
    { value: 'AIChatbots', label: 'AI Chatbots' },
    { value: 'CloudSecurity', label: 'Cloud Security' },
    { value: 'QuantumComputing', label: 'Quantum Computing' },
    { value: 'DataEngineering', label: 'Data Engineering' },
    { value: 'SQL', label: 'SQL' }, // SQL added
    { value: 'Python', label: 'Python' },
    { value: 'Java', label: 'Java' },
    { value: 'C++', label: 'C++' },
    { value: 'Ruby', label: 'Ruby' },
    { value: 'PHP', label: 'PHP' },
    { value: 'Swift', label: 'Swift' },
    { value: 'JavaScript', label: 'JavaScript' },
    { value: 'ReactJS', label: 'ReactJS' },
    { value: 'AngularJS', label: 'AngularJS' },
    { value: 'VueJS', label: 'VueJS' },
    { value: 'Node.js', label: 'Node.js' },
    { value: 'Django', label: 'Django' },
    { value: 'ASP.NET', label: 'ASP.NET' },
  ];

  export const jobModeOptions = [
  { value: 'FTE', label: 'FTE' },
  { value: 'Contract', label: 'Contract' },
  { value: 'C2H', label: 'C2H' },
];

export const modeOptions = [
  { value: 'Work from Home', label: 'Work from Home' },
  { value:  'Work from Office', label: 'Work from Office' },
  { value: 'Hybrid', label: 'Hybrid' },
];
export const customStyles = {
  control: (provided, state) => ({
    ...provided,
    width: '100%', // Adjust the width as needed
    borderColor: state.isFocused ? 'rgb(145, 125, 145)' : 'rgb(128, 128, 128)', // Yellow border color on focus, gray when not focused
  }),
  option: (provided, state) => ({
    ...provided,
    backgroundColor: state.isFocused ? 'rgb(142, 147, 230)' : 'white', // Light blue background color on hover/focus, white when not focused
    color: state.isFocused ? 'rgb(896, 596, 255)' : 'black', // Blue text color on hover/focus, black when not focused
  }),
  // Add more custom styles as needed
};