  // Add IDs to your tech stack options
  export const techStackOptions = [
    { value: 'WebDevelopment', label: 'Web Development' },
    { value: 'MobileAppDevelopment', label: 'Mobile App Development' },
    { value: 'DataScience', label: 'Data Science' },
    { value: 'MachineLearning', label: 'Machine Learning' },
    { value: 'ArtificialIntelligence', label: 'Artificial Intelligence' },
    { value: 'CloudComputing', label: 'Cloud Computing' },
    { value: 'Cybersecurity', label: 'Cybersecurity' },
    { value: 'DatabaseManagement', label: 'Database Management' },
    { value: 'DevOps', label: 'DevOps' },
    { value: 'FullStackDevelopment', label: 'Full Stack Development' },
    { value: 'FrontendDevelopment', label: 'Frontend Development' },
    { value: 'BackendDevelopment', label: 'Backend Development' },
    { value: 'UIUXDesign', label: 'UI/UX Design' },
    { value: 'BigData', label: 'Big Data' },
    { value: 'Blockchain', label: 'Blockchain' },
    { value: 'IoT', label: 'Internet of Things (IoT)' },
    { value: 'ARVRDevelopment', label: 'AR/VR Development' },
    { value: 'Robotics', label: 'Robotics' },
    { value: 'GameDevelopment', label: 'Game Development' },
    { value: 'NetworkAdministration', label: 'Network Administration' },
    { value: 'SystemAdministration', label: 'System Administration' },
    { value: 'SoftwareTesting', label: 'Software Testing' },
    { value: 'ITConsulting', label: 'IT Consulting' },
    { value: 'E-commerce', label: 'E-commerce' },
    { value: 'HealthIT', label: 'Health IT' },
    { value: 'FinancialTechnology', label: 'Financial Technology (FinTech)' },
    { value: 'EducationalTechnology', label: 'Educational Technology (EdTech)' },
    { value: 'AIChatbots', label: 'AI Chatbots' },
    { value: 'CloudSecurity', label: 'Cloud Security' },
    { value: 'QuantumComputing', label: 'Quantum Computing' },
    { value: 'DataEngineering', label: 'Data Engineering' },
    { value: 'RemoteSensing', label: 'Remote Sensing' },
    { value: 'Virtualization', label: 'Virtualization' },
    { value: 'EmbeddedSystems', label: 'Embedded Systems' },
    { value: 'Bioinformatics', label: 'Bioinformatics' },
    { value: 'GeographicInformationSystems', label: 'Geographic Information Systems (GIS)' },
    { value: 'CloudStorage', label: 'Cloud Storage' },
    { value: 'WirelessCommunication', label: 'Wireless Communication' },
    { value: 'WebDesign', label: 'Web Design' },
    { value: 'DataAnalytics', label: 'Data Analytics' },
    { value: 'BusinessIntelligence', label: 'Business Intelligence' },
    { value: 'CRMSoftware', label: 'CRM Software' },
    { value: 'SupplyChainManagement', label: 'Supply Chain Management' },
    { value: 'Telecommunications', label: 'Telecommunications' },
    { value: 'SaaS', label: 'Software as a Service (SaaS)' },
    { value: 'PaaS', label: 'Platform as a Service (PaaS)' },
    { value: 'IaaS', label: 'Infrastructure as a Service (IaaS)' },
    { value: 'MobileAppDevelopment', label: 'Mobile App Development' },
    { value: 'DataScience', label: 'Data Science' },
    { value: 'MachineLearning', label: 'Machine Learning' },
    { value: 'ArtificialIntelligence', label: 'Artificial Intelligence' },
    { value: 'CloudComputing', label: 'Cloud Computing' },
    { value: 'Cybersecurity', label: 'Cybersecurity' },
    { value: 'DatabaseManagement', label: 'Database Management' },
    { value: 'DevOps', label: 'DevOps' },
    { value: 'FullStackDevelopment', label: 'Full Stack Development' },
    { value: 'FrontendDevelopment', label: 'Frontend Development' },
    { value: 'BackendDevelopment', label: 'Backend Development' },
    { value: 'UIUXDesign', label: 'UI/UX Design' },
    { value: 'BigData', label: 'Big Data' },
    { value: 'Blockchain', label: 'Blockchain' },
    { value: 'IoT', label: 'Internet of Things (IoT)' },
    { value: 'ARVRDevelopment', label: 'AR/VR Development' },
    { value: 'Robotics', label: 'Robotics' },
    { value: 'GameDevelopment', label: 'Game Development' },
    { value: 'NetworkAdministration', label: 'Network Administration' },
    { value: 'SystemAdministration', label: 'System Administration' },
    { value: 'SoftwareTesting', label: 'Software Testing' },
    { value: 'ITConsulting', label: 'IT Consulting' },
    { value: 'E-commerce', label: 'E-commerce' },
    { value: 'HealthIT', label: 'Health IT' },
    { value: 'FinancialTechnology', label: 'Financial Technology (FinTech)' },
    { value: 'EducationalTechnology', label: 'Educational Technology (EdTech)' },
    { value: 'AIChatbots', label: 'AI Chatbots' },
    { value: 'CloudSecurity', label: 'Cloud Security' },
    { value: 'QuantumComputing', label: 'Quantum Computing' },
    { value: 'DataEngineering', label: 'Data Engineering' },
    { value: 'SQL', label: 'SQL' }, // SQL added
    { value: 'Python', label: 'Python' },
    { value: 'Java', label: 'Java' },
    { value: 'C++', label: 'C++' },
    { value: 'Ruby', label: 'Ruby' },
    { value: 'PHP', label: 'PHP' },
    { value: 'Swift', label: 'Swift' },
    { value: 'JavaScript', label: 'JavaScript' },
    { value: 'ReactJS', label: 'ReactJS' },
    { value: 'AngularJS', label: 'AngularJS' },
    { value: 'VueJS', label: 'VueJS' },
    { value: 'Node.js', label: 'Node.js' },
    { value: 'Django', label: 'Django' },
    { value: 'ASP.NET', label: 'ASP.NET' },
  ];

  export const jobModeOptions = [
  { value: 'FTE', label: 'FTE' },
  { value: 'Contract', label: 'Contract' },
  { value: 'C2H', label: 'C2H' },
];

export const modeOptions = [
  { value: 'Work from Home', label: 'Work from Home' },
  { value:  'Work from Office', label: 'Work from Office' },
  { value: 'Hybrid', label: 'Hybrid' },
];

export const indianStateswithmetropolitanCities = [
  { value: 'Andhra Pradesh', label: 'Andhra Pradesh' },
  { value: 'Ladakh', label: 'Ladakh' },
  { value: 'Arunachal Pradesh', label: 'Arunachal Pradesh' },
  { value: 'Assam', label: 'Assam' },
  { value: 'Bihar', label: 'Bihar' },
  { value: 'Chhattisgarh', label: 'Chhattisgarh' },
  { value: 'Goa', label: 'Goa' },
  { value: 'Gujarat', label: 'Gujarat' },
  { value: 'Haryana', label: 'Haryana' },
  { value: 'Himachal Pradesh', label: 'Himachal Pradesh' },
  { value: 'Jharkhand', label: 'Jharkhand' },
  { value: 'Karnataka', label: 'Karnataka' },
  { value: 'Kerala', label: 'Kerala' },
  { value: 'Madhya Pradesh', label: 'Madhya Pradesh' },
  { value: 'Maharashtra', label: 'Maharashtra' },
  { value: 'Manipur', label: 'Manipur' },
  { value: 'Meghalaya', label: 'Meghalaya' },
  { value: 'Mizoram', label: 'Mizoram' },
  { value: 'Nagaland', label: 'Nagaland' },
  { value: 'Odisha', label: 'Odisha' },
  { value: 'Punjab', label: 'Punjab' },
  { value: 'Rajasthan', label: 'Rajasthan' },
  { value: 'Sikkim', label: 'Sikkim' },
  { value: 'Tamil Nadu', label: 'Tamil Nadu' },
  { value: 'Telangana', label: 'Telangana' },
  { value: 'Tripura', label: 'Tripura' },
  { value: 'Uttar Pradesh', label: 'Uttar Pradesh' },
  { value: 'Uttarakhand', label: 'Uttarakhand' },
  { value: 'West Bengal', label: 'West Bengal' },
  { value: 'Andaman and Nicobar Islands', label: 'Andaman and Nicobar Islands' },
  { value: 'Chandigarh', label: 'Chandigarh' },
  { value: 'Dadra and Nagar Haveli and Daman and Diu', label: 'Dadra and Nagar Haveli and Daman and Diu' },
  { value: 'Lakshadweep', label: 'Lakshadweep' },
  { value: 'Puducherry', label: 'Puducherry' },
  { value: 'Bengaluru', label: 'Bengaluru' },
  { value: 'Chennai', label: 'Chennai' },
  { value: 'Hyderabad', label: 'Hyderabad' },
  { value: 'Kolkata', label: 'Kolkata' },
  { value: 'Pune', label: 'Pune' },
  { value: 'Ahmedabad', label: 'Ahmedabad' },
  { value: 'Surat', label: 'Surat' },
  { value: 'Jaipur', label: 'Jaipur' },
  { value: 'Lucknow', label: 'Lucknow' },
  { value: 'Kanpur', label: 'Kanpur' },
  { value: 'Nagpur', label: 'Nagpur' },
  { value: 'Patna', label: 'Patna' },
  { value: 'Indore', label: 'Indore' },
  { value: 'Thane', label: 'Thane' },
  { value: 'Bhopal', label: 'Bhopal' },
  { value: 'Visakhapatnam', label: 'Visakhapatnam' },
  { value: 'Vadodara', label: 'Vadodara' },
  { value: 'Firozabad', label: 'Firozabad' },
  { value: 'Ludhiana', label: 'Ludhiana' },
  { value: 'Rajkot', label: 'Rajkot' },
  { value: 'Agra', label: 'Agra' },
  { value: 'Siliguri', label: 'Siliguri' },
  { value: 'Nashik', label: 'Nashik' },
  { value: 'Faridabad', label: 'Faridabad' },
  { value: 'Patiala', label: 'Patiala' },
  { value: 'Meerut', label: 'Meerut' },
  { value: 'Kalyan-Dombivli', label: 'Kalyan-Dombivli' },
  { value: 'Vasai-Virar', label: 'Vasai-Virar' },
  { value: 'Varanasi', label: 'Varanasi' },
  { value: 'Srinagar', label: 'Srinagar' },
  { value: 'Dhanbad', label: 'Dhanbad' },
  { value: 'Jodhpur', label: 'Jodhpur' },
  { value: 'Amritsar', label: 'Amritsar' },
  { value: 'Raipur', label: 'Raipur' },
  { value: 'Allahabad', label: 'Allahabad' },
  { value: 'Coimbatore', label: 'Coimbatore' },
  { value: 'Jabalpur', label: 'Jabalpur' },
  { value: 'Gwalior', label: 'Gwalior' },
  { value: 'Vijayawada', label: 'Vijayawada' },
  { value: 'Madurai', label: 'Madurai' },
  { value: 'Guwahati', label: 'Guwahati' },
  { value: 'Hubli-Dharwad', label: 'Hubli-Dharwad' },
  { value: 'Mysuru', label: 'Mysuru' },
  { value: 'Tirunelveli', label: 'Tirunelveli' },
  { value: 'Bareilly', label: 'Bareilly' },
  { value: 'Bhavnagar', label: 'Bhavnagar' },
  { value: 'Bikaner', label: 'Bikaner' },
  { value: 'Bokaro Steel City', label: 'Bokaro Steel City' },
  { value: 'Bangalore', label: 'Bangalore' },
  { value: 'Amaravati', label: 'Amaravati' }, 
  { value: 'Itanagar', label: 'Itanagar' }, 
  { value: 'Dispur', label: 'Dispur' },
  { value: 'Patna', label: 'Patna' }, 
  { value: 'Raipur', label: 'Raipur' }, 
  { value: 'Panaji', label: 'Panaji' }, 
  { value: 'Gandhinagar', label: 'Gandhinagar' }, 
  { value: 'Shimla', label: 'Shimla' }, 
  { value: 'Ranchi', label: 'Ranchi' },
  { value: 'Thiruvananthapuram', label: 'Thiruvananthapuram' }, 
  { value: 'Bhopal', label: 'Bhopal' }, 
  { value: 'Mumbai', label: 'Mumbai' }, 
  { value: 'Imphal', label: 'Imphal' },
  { value: 'Shillong', label: 'Shillong' }, 
  { value: 'Aizawl', label: 'Aizawl' }, 
  { value: 'Kohima', label: 'Kohima' }, 
  { value: 'Bhubaneswar', label: 'Bhubaneswar' }, 
  { value: 'Jaipur', label: 'Jaipur' }, 
  { value: 'Gangtok', label: 'Gangtok' },  
  { value: 'Agartala', label: 'Agartala' }, 
  { value: 'Lucknow', label: 'Lucknow' },
  { value: 'Dehradun', label: 'Dehradun' }, 
  { value: 'Kolkata', label: 'Kolkata' }, 
  { value: 'Port Blair', label: 'Port Blair' }, 
  { value: 'Delhi', label: 'Delhi' }, 
  
];


export const customStyles = {
  control: (provided, state) => ({
    ...provided,
    width: '100%', // Adjust the width as needed
    borderColor: state.isFocused ? 'rgb(145, 125, 145)' : 'rgb(128, 128, 128)', // Yellow border color on focus, gray when not focused
  }),
  option: (provided, state) => ({
    ...provided,
    backgroundColor: state.isFocused ? 'rgb(142, 147, 230)' : 'white', // Light blue background color on hover/focus, white when not focused
    color: state.isFocused ? 'rgb(896, 596, 255)' : 'black', // Blue text color on hover/focus, black when not focused
  }),
  // Add more custom styles as needed
};